name: diz_flutter_core
description: >
  A common used classes for internal projects. Also can used in other projects

version: 1.0.0

homepage: https://github.com/DizoftTeam/diz-flutter-core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1

dev_dependencies:
  pedantic: ^1.9.0
  lint: ^1.3.0
